site_name: Wildlife Tools

theme:
  name: "material"

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_tools]
          options:
            annotations_path: brief



nav:
  - Introduction: index.md  
  - Wildlife Dataset: wildlife_dataset.md
  - Train: training.md
  - Feature Extraction: features.md
  - Similarity: similarity.md
  - Evaluation: evaluation.md
  - Benchmarks:
    - Overview: benchmark.md
 