# Dataset
datasets:
    method: folder
    path: /home/cermavo3/projects/turtles/experiments_compare_datasets/data/SeaTurtleIDHeads
    datasets:
        dataset_database:
            split: train
            transform: transform
        dataset_query:
            split: test
            transform: transform

splitter:
    method: open_set
    seed: 1
    ratio_train: 0.5
    ratio_class_test: 0.2

transform:
    method: torchvision
    compose:
        - Resize(size=256)
        - CenterCrop(size=(224, 224))
        - ToTensor()
        - Grayscale()

# Model
trainer:
    method: loftr_matcher
    pretrained: outdoor
    thresholds:
        - 0.99
        - 0.95
        - 0.9
        - 0.8
        - 0.5 
    chunk: 1
    chunk_total: 5
    device: 'cuda'
    batch_size: 128
