pipeline:
  workdir: 'test/'
  method: SimilarityPipeline


  database:
    method: WildlifeDataset
    metadata: examples/SampleDataset/metadata.csv
    root: examples/SampleDataset
    transform:
      method: TransformTorchvision
      compose:
        - Resize(size=256)
        - CenterCrop(size=(224, 224))
        - Grayscale()
    split:
      method: SplitMetadata
      col: split
      value: train


  query:
    method: WildlifeDataset
    metadata: examples/SampleDataset/metadata.csv
    root: examples/SampleDataset
    transform:
      method: TransformTorchvision
      compose:
        - Resize(size=256)
        - CenterCrop(size=(224, 224))
        - Grayscale()
    split:
      method: SplitPipeline
      steps:
        - method: SplitMetadata
          col: split
          value: test
        - method: SplitChunk
          chunk: 2
          chunk_total: 3


  extractor:
    method: SIFTFeatures


  similarity:
    method: MatchDescriptors
    descriptor_dim: 128
    thresholds:
      - 0.2
      - 0.4
      - 0.6
      - 0.8
